export const airdrops = [
    {
        id: 1,
        name: "Solana",
        logo: "/partners/Solana.svg",
        value: "$150",
        status: "Active",
        type: "Featured",
        description: "Participate in the Solana ecosystem airdrop.",
    },
    {
        id: 2,
        name: "Raydium",
        logo: "/partners/raydium.svg",
        value: "$50",
        status: "Active",
        type: "DeFi",
        description: "Trade on Raydium to be eligible.",
    },
    {
        id: 3,
        name: "Pumpfun",
        logo: "/partners/pumpfun.svg",
        value: "Unknown",
        status: "Upcoming",
        type: "Meme",
        description: "Join the Pumpfun community early.",
    },
    {
        id: 4,
        name: "Coinbase",
        logo: "/partners/coinbase.svg",
        value: "$20",
        status: "Active",
        type: "Exchange",
        description: "Learn and earn with Coinbase.",
    },
    {
        id: 5,
        name: "Polygon",
        logo: "/partners/Polygon.svg",
        value: "$10",
        status: "Ended",
        type: "Layer 2",
        description: "Polygon zkEVM saga.",
    },
    {
        id: 6,
        name: "Sei",
        logo: "/partners/Sei.svg",
        value: "$500",
        status: "Active",
        type: "Layer 1",
        description: "Sei Network atlantic rewards.",
    },
];
